# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogspost_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='author',
            field=models.CharField(default='Timi', max_length=50),
        ),
    ]
