# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogspost_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='classification',
            field=models.CharField(default='\u539f\u521b', max_length=10),
        ),
    ]
